#!/bin/bash
echo "🚀 ФИНАЛЬНЫЙ ДЕПЛОЙМЕНТ - Пересборка Docker образа"
echo "=================================================="

echo ""
echo "✅ GIT PULL ВЫПОЛНЕН - все фиксы есть в коде"
echo "❌ DOCKER REBUILD НЕ ВЫПОЛНЕН - запущен старый образ"
echo ""
echo "🐳 ВЫПОЛНИТЕ ЭТИ КОМАНДЫ НА ПРОДАКШЕНЕ:"
echo ""
echo "   1. Остановить сервисы:"
echo "      docker-compose down"
echo ""
echo "   2. Пересобрать ai-service с новым кодом:"
echo "      docker-compose build --no-cache ai-service"
echo ""
echo "   3. Запустить обновленные сервисы:"
echo "      docker-compose up -d"
echo ""
echo "   4. Проверить логи (30-60 секунд):"
echo "      docker logs ai-service -f"
echo ""
echo "✅ ОЖИДАЕМЫЕ ИЗМЕНЕНИЯ В ЛОГАХ:"
echo "   - НЕТ 'Cannot connect to host localhost:9200'"
echo "   - НЕТ 'AC search failed'"
echo "   - ЕСТЬ успешные подключения к elasticsearch:9200"
echo ""
echo "🧪 ТЕСТ ПОСЛЕ RESTART:"
echo '   curl -X POST http://95.217.84.234:8002/process \'
echo '     -H "Content-Type: application/json" \'
echo '     -d "{\"text\": \"Петро Порошенко\"}" | jq ".decision.risk_level"'
echo ""
echo "✅ ОЖИДАЕМЫЙ РЕЗУЛЬТАТ:"
echo '   "high"  # Вместо "low"'
echo ""
echo "🎯 ПОСЛЕ REBUILD ВСЕ 5 ФИКСОВ ЗАРАБОТАЮТ!"
