#!/bin/bash
# URGENT: Fix production Elasticsearch and decision engine

echo "🚨 URGENT PRODUCTION FIX - Decision Engine + Elasticsearch"
echo "=========================================================="

PROD_HOST="95.217.84.234"
PROD_USER="root"

echo ""
echo "📋 MANUAL DEPLOYMENT INSTRUCTIONS:"
echo ""
echo "🔗 Connect to production server:"
echo "   ssh root@95.217.84.234"
echo ""
echo "📍 Navigate to project directory:"
echo "   cd /root/ai-service"
echo ""
echo "🔄 Pull latest code (contains decision engine fix):"
echo "   git pull origin main"
echo ""
echo "💾 Alternative: Manual edit decision_engine.py at line ~60:"
echo "   # Add this line to DecisionInput():"
echo "   search=inp.search"
echo ""
echo "🐳 Rebuild and restart services:"
echo "   docker-compose down"
echo "   docker-compose build --no-cache ai-service"
echo "   docker-compose up -d"
echo ""
echo "⏱️ Wait for services to start (30-60 seconds)"
echo "   docker logs ai-service -f"
echo ""
echo "🧪 Test the fix:"
echo "   curl -X POST http://95.217.84.234:8002/process \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"text\": \"Петро Порошенко\"}' | jq '.decision.score_breakdown'"
echo ""
echo "✅ Expected result AFTER fix:"
echo "   {"
echo "     \"search_contribution\": 0.25,     # ← SHOULD APPEAR!"
echo "     \"smartfilter_contribution\": 0.075,"
echo "     \"person_contribution\": 0.18,"
echo "     \"total\": 0.505                   # ← risk_level becomes medium/high"
echo "   }"
echo ""
echo "❌ Current BROKEN result (before fix):"
echo "   {"
echo "     \"smartfilter_contribution\": 0.075,"
echo "     \"person_contribution\": 0.18,"
echo "     \"total\": 0.255                   # ← missing search_contribution!"
echo "   }"
echo ""
echo "🔍 If search still returns 0 hits after fix:"
echo "   # Check Elasticsearch connectivity"
echo "   docker exec ai-service curl http://localhost:9200/_cluster/health"
echo "   "
echo "   # Check if patterns exist"
echo "   curl 'http://95.217.84.234:9200/ai_service_ac_patterns/_search' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"query\": {\"wildcard\": {\"pattern\": \"*порошенко*\"}}, \"size\": 3}'"
echo ""
echo "🚀 BUSINESS IMPACT:"
echo "   BEFORE: AC finds sanctions → still 'low risk' → FALSE NEGATIVE ❌"
echo "   AFTER:  AC finds sanctions → 'high risk' → CORRECT DETECTION ✅"
echo ""
echo "🔴 CRITICAL: Direct sanctions matches are NOT being blocked!"
echo ""
