#!/usr/bin/env python3
"""Load reviewed exports using the same schema, model contract and jobs as the API.

Supply --patterns-file, --vectors-file, or the manifest generated by
prepare_sanctions_data.py. Connection/authentication settings come from ES_*.
A rejected bulk item or invalid embedding produces a nonzero exit status.
"""

import argparse
import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from elasticsearch import AsyncElasticsearch
from ai_service.api.admin_endpoints import _load_documents, loading_status
from ai_service.layers.search.config import HybridSearchConfig
from ai_service.layers.search.elasticsearch_client import build_client_kwargs
from ai_service.layers.search.index_schema import (
    pattern_document,
    vector_document,
    embedding_contract,
)

if __package__:
    from .create_empty_indices import (
        configure_target,
        create_ac_patterns_index,
        create_vectors_index,
    )
else:
    from create_empty_indices import (
        configure_target,
        create_ac_patterns_index,
        create_vectors_index,
    )


def read_export(path):
    with Path(path).open(encoding="utf-8") as stream:
        return json.load(stream)


def category_for(item):
    entity_type = item.get("entity_type") or (item.get("metadata") or {}).get(
        "entity_type"
    )
    category = item.get("category")
    if category in {"person", "company", "terrorism"}:
        return category
    if entity_type in {"company", "organization", "legal_entity"}:
        return "company"
    if entity_type in {"person", "individual", "terrorism"}:
        return "terrorism" if entity_type == "terrorism" else "person"
    raise ValueError("Every export row must identify its entity type")


async def bulk_load_patterns(es_host, index_name, patterns_file, batch_size=1000):
    configure_target(es_host)
    config = HybridSearchConfig.from_env()
    if index_name != config.elasticsearch.ac_index:
        raise ValueError("Target must match the configured AC index")
    payload = read_export(patterns_file)
    rows = payload.get("patterns", []) if isinstance(payload, dict) else payload
    if not isinstance(rows, list) or not rows:
        raise ValueError("AC export is empty or malformed")
    documents = [
        pattern_document(row, category_for(row), row.get("tier", 0)) for row in rows
    ]
    await _load_documents(documents, "ac_patterns", batch_size=batch_size)
    return loading_status["ac_patterns"]["status"] == "completed"


async def bulk_load_vectors(es_host, index_name, vectors_file, batch_size=500):
    configure_target(es_host)
    config = HybridSearchConfig.from_env()
    if index_name != config.elasticsearch.vector_index:
        raise ValueError("Target must match the configured vector index")
    rows = read_export(vectors_file)
    if not isinstance(rows, list) or not rows:
        raise ValueError("Vector export is empty or malformed")
    model = embedding_contract()["model_name"]
    documents = [vector_document(row, category_for(row), model) for row in rows]
    await _load_documents(documents, "vectors", vectors=True, batch_size=batch_size)
    return loading_status["vectors"]["status"] == "completed"


def manifest_files(path):
    manifest = read_export(path)
    generated = manifest.get("generated_files", {})
    root = Path(__file__).resolve().parents[1]

    def resolve(value):
        if not value:
            return None
        candidate = Path(value)
        if candidate.is_absolute():
            return candidate
        # Existing prepare_sanctions_data manifests store repository-relative paths.
        return root / candidate

    return resolve(generated.get("ac_patterns")), resolve(generated.get("vectors"))


async def main_async(args):
    config = configure_target(args.es_host, args.index_prefix)
    patterns, vectors = args.patterns_file, args.vectors_file
    if args.manifest:
        manifest_patterns, manifest_vectors = manifest_files(args.manifest)
        patterns, vectors = patterns or manifest_patterns, vectors or manifest_vectors
    if not patterns and not vectors:
        raise ValueError("Supply an explicit export file or deployment manifest")
    if patterns and not await bulk_load_patterns(
        None, config.elasticsearch.ac_index, patterns, args.batch_size
    ):
        return 1
    if vectors and not await bulk_load_vectors(
        None, config.elasticsearch.vector_index, vectors, args.batch_size
    ):
        return 1
    if args.create_vector_indices and not vectors:
        await create_vectors_index(None, config.elasticsearch.vector_index)
    if not args.skip_warmup:
        async with AsyncElasticsearch(
            **build_client_kwargs(config.elasticsearch)
        ) as client:
            index = (
                config.elasticsearch.ac_index
                if patterns
                else config.elasticsearch.vector_index
            )
            await client.search(index=index, size=0, query={"match_all": {}})
    print(
        "Requested exports loaded successfully; check /health/ready for complete service readiness."
    )
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--es-host")
    parser.add_argument("--index-prefix")
    parser.add_argument("--patterns-file", type=Path)
    parser.add_argument("--vectors-file", type=Path)
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--batch-size", type=int, default=500)
    parser.add_argument("--create-vector-indices", action="store_true")
    parser.add_argument("--skip-warmup", action="store_true")
    return asyncio.run(main_async(parser.parse_args()))


if __name__ == "__main__":
    raise SystemExit(main())
